export let columns = [
    {
      "Unnamed: 0": 0,
      "id": "evcloud.00009",
      "access": "r",
      "basetype": "int",
      "description": "Valve Type",
      "format": "application/vnd.belimo.enum;0|1",
      "name": "ValveType",
      "privacy": false,
      "restriction": "uint8",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 1,
      "id": "evcloud.10",
      "access": "r",
      "basetype": "int",
      "description": "DN Size of Valve",
      "format": "",
      "name": "DN_Size",
      "privacy": false,
      "restriction": "int32",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 2,
      "id": "evcloud.100",
      "access": "r",
      "basetype": "real",
      "description": "Relative Flow in %",
      "format": "",
      "name": "RelFlow_Fb_Rel2Vmax",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 3,
      "id": "evcloud.110",
      "access": "r",
      "basetype": "real",
      "description": "Absolute Flow in m3/s",
      "format": "",
      "name": "AbsFlow_Fb_m3s",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "cubicMetrePerSecond"
    },
    {
      "Unnamed: 0": 4,
      "id": "evcloud.120",
      "access": "rw",
      "basetype": "real",
      "description": "Maximum Power Limit in %",
      "format": "",
      "name": "Pmax_Rel_Write",
      "privacy": false,
      "restriction": "[0.5,100]",
      "definedBy": "evcloud/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 5,
      "id": "evcloud.130",
      "access": "r",
      "basetype": "real",
      "description": "Relative Power %",
      "format": "",
      "name": "RelPower_Fb_Rel2Pmax",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 6,
      "id": "evcloud.140",
      "access": "r",
      "basetype": "real",
      "description": "Absolute Power in W",
      "format": "",
      "name": "AbsPower_Fb_W",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "watt"
    },
    {
      "Unnamed: 0": 7,
      "id": "evcloud.150",
      "access": "r",
      "basetype": "real",
      "description": "Temperature 1 remote in K",
      "format": "",
      "name": "T1_remote_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "kelvin"
    },
    {
      "Unnamed: 0": 8,
      "id": "evcloud.160",
      "access": "r",
      "basetype": "real",
      "description": "Temperature 2 embeded in K",
      "format": "",
      "name": "T2_embeded_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "kelvin"
    },
    {
      "Unnamed: 0": 9,
      "id": "evcloud.170",
      "access": "rw",
      "basetype": "int",
      "description": "Delta T Limitation Type",
      "format": "application/vnd.belimo.enum;1|2|3",
      "name": "DeltaT_Limitation_Write",
      "privacy": false,
      "restriction": "uint8",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 10,
      "id": "evcloud.180",
      "access": "r",
      "basetype": "real",
      "description": "Applied Setpoint DeltaT in K",
      "format": "",
      "name": "SpDeltaT_applied_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "differentialKelvin"
    },
    {
      "Unnamed: 0": 11,
      "id": "evcloud.190",
      "access": "r",
      "basetype": "real",
      "description": "Delta Temperature in K",
      "format": "",
      "name": "DeltaT_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "differentialKelvin"
    },
    {
      "Unnamed: 0": 12,
      "id": "evcloud.20",
      "access": "rw",
      "basetype": "int",
      "description": "Control Mode",
      "format": "application/vnd.belimo.enum;1|2|3",
      "name": "ControlMode_Write",
      "privacy": false,
      "restriction": "int32",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 13,
      "id": "evcloud.200",
      "access": "r",
      "basetype": "real",
      "description": "Cooling Energy in J",
      "format": "",
      "name": "Cooling_E_J",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "joule"
    },
    {
      "Unnamed: 0": 14,
      "id": "evcloud.210",
      "access": "r",
      "basetype": "real",
      "description": "Heating Energy in J",
      "format": "",
      "name": "Heating_E_J",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "joule"
    },
    {
      "Unnamed: 0": 15,
      "id": "evcloud.220",
      "access": "r",
      "basetype": "real",
      "description": "Err_State_Cloud_(MSB=FreezeWarn|MP2_nAlive|RevFlow|BPosG|P_Dmd_nReached|V_Dmd_nReached|Airbubbles|Flow_with_closed_Valve|Actuator_Stalled|Flow_Signal_Faulty|T2_Err|LSB=T1_Err)",
      "format": "",
      "name": "Error_Status_Cloud",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 17,
      "id": "evcloud.240",
      "access": "rw",
      "basetype": "real",
      "description": "Setpoint Delta T in K",
      "format": "",
      "name": "SpDeltaT_K_Write",
      "privacy": false,
      "restriction": "[1,55.556]",
      "definedBy": "evcloud/1.2",
      "unit": "differentialKelvin"
    },
    {
      "Unnamed: 0": 18,
      "id": "evcloud.250",
      "access": "rw",
      "basetype": "real",
      "description": "Setpoint Flow in m3/s at Delta T",
      "format": "",
      "name": "SpFlow_DeltaT_lmin_Write",
      "privacy": false,
      "restriction": "[0,0.1]",
      "definedBy": "evcloud/1.2",
      "unit": "cubicMetrePerSecond"
    },
    {
      "Unnamed: 0": 19,
      "id": "evcloud.251",
      "access": "r",
      "basetype": "real",
      "description": "Operating Time in h",
      "format": "",
      "name": "OperatingHours",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 20,
      "id": "evcloud.252",
      "access": "rw",
      "basetype": "real",
      "description": "Cloud Live Time in h",
      "format": "",
      "name": "CloudLiveHours",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 21,
      "id": "evcloud.30",
      "access": "rw",
      "basetype": "int",
      "description": "Override Control",
      "format": "application/vnd.belimo.enum;1|2|3|4|5|6|7|8|11",
      "name": "Override_Write",
      "privacy": false,
      "restriction": "int32",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 22,
      "id": "evcloud.40",
      "access": "rw",
      "basetype": "int",
      "description": "Installation Position",
      "format": "application/vnd.belimo.enum;1|2",
      "name": "InstallationPosition_Write",
      "privacy": false,
      "restriction": "uint8",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 23,
      "id": "evcloud.50",
      "access": "rw",
      "basetype": "int",
      "description": "Setpoint Source",
      "format": "application/vnd.belimo.enum;1|2",
      "name": "SpSource_Write",
      "privacy": false,
      "restriction": "int32",
      "definedBy": "evcloud/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 24,
      "id": "evcloud.60",
      "access": "rw",
      "basetype": "real",
      "description": "Setpoint Relative in %",
      "format": "",
      "name": "DDC_BUS_Sp_Write",
      "privacy": false,
      "restriction": "[0,100]",
      "definedBy": "evcloud/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 25,
      "id": "evcloud.70",
      "access": "r",
      "basetype": "real",
      "description": "Setpoint Analog in Volt, only when Sp_Source=Analog  0-12V",
      "format": "",
      "name": "DDC_Sp_V",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "volt"
    },
    {
      "Unnamed: 0": 26,
      "id": "evcloud.80",
      "access": "r",
      "basetype": "real",
      "description": "Relative Position in %",
      "format": "",
      "name": "RelPos_Fb",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloud/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 27,
      "id": "evcloud.90",
      "access": "rw",
      "basetype": "real",
      "description": "Maximum Flow Limit in %",
      "format": "",
      "name": "Vmax_Rel_Write",
      "privacy": false,
      "restriction": "[30,100]",
      "definedBy": "evcloud/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 28,
      "id": "evcloudplus.172",
      "access": "r",
      "basetype": "real",
      "description": "Upper_Control_Band_4_Flow_Rel_2_Vnom",
      "format": "",
      "name": "Upper_Control_Band_4_Flow",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 29,
      "id": "evcloudplus.173",
      "access": "r",
      "basetype": "real",
      "description": "Lower_Control_Band_4_Flow_Rel_2_Vnom",
      "format": "",
      "name": "Lower_Control_Band_4_Flow",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 30,
      "id": "evcloudplus.260",
      "access": "r",
      "basetype": "real",
      "description": "Operating_Time_h",
      "format": "",
      "name": "Operating_Time_h_Research",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 31,
      "id": "evcloudplus.261",
      "access": "r",
      "basetype": "real",
      "description": "Active_Time_h",
      "format": "",
      "name": "Active_Time_h",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 32,
      "id": "evcloudplus.269",
      "access": "r",
      "basetype": "real",
      "description": "V_Sp_Rel_2_Vnom",
      "format": "",
      "name": "V_Sp_Rel_2_Vnom",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 33,
      "id": "evcloudplus.270",
      "access": "r",
      "basetype": "real",
      "description": "Start_And_Stop_Ratio_Rel",
      "format": "",
      "name": "Start_And_Stop_Ratio_Rel",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 34,
      "id": "evcloudplus.359",
      "access": "r",
      "basetype": "real",
      "description": "dT_upper_deadbandLim_K",
      "format": "",
      "name": "dT_upper_dBLim_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "differentialKelvin"
    },
    {
      "Unnamed: 0": 35,
      "id": "evcloudplus.36",
      "access": "r",
      "basetype": "real",
      "description": "RelPos_Sp",
      "format": "",
      "name": "RelPos_Sp",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 36,
      "id": "evcloudplus.360",
      "access": "r",
      "basetype": "real",
      "description": "dT_lower_deadBandLim_K",
      "format": "",
      "name": "dT_lower_dBLim_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "differentialKelvin"
    },
    {
      "Unnamed: 0": 37,
      "id": "evcloudplus.366",
      "access": "r",
      "basetype": "int",
      "description": "Sequence_(1=NoDmd|2=Cooling|3=Heating)",
      "format": "",
      "name": "Sequence_Ste",
      "privacy": false,
      "restriction": "int32",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 38,
      "id": "evcloudplus.37",
      "access": "r",
      "basetype": "real",
      "description": "DDC_Sp_Rel",
      "format": "",
      "name": "DDC_Sp_Rel",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 39,
      "id": "evcloudplus.381",
      "access": "r",
      "basetype": "real",
      "description": "last_copleted_month_average",
      "format": "",
      "name": "dT_avg_last_month_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "differentialKelvin"
    },
    {
      "Unnamed: 0": 40,
      "id": "evcloudplus.382",
      "access": "r",
      "basetype": "real",
      "description": "Flow_Volume_Heating_total_m3",
      "format": "",
      "name": "Flow_Volume_Heating_total_m3",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "cubicMetrePerSecond"
    },
    {
      "Unnamed: 0": 41,
      "id": "evcloudplus.383",
      "access": "r",
      "basetype": "real",
      "description": "Flow_Volume_Cooling_total_m3",
      "format": "",
      "name": "Flow_Volume_Cooling_total_m3",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "cubicMetrePerSecond"
    },
    {
      "Unnamed: 0": 42,
      "id": "evcloudplus.384",
      "access": "r",
      "basetype": "real",
      "description": "while_DDC_Sp_greater_0",
      "format": "",
      "name": "Active_dT_Manager_total_h",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 43,
      "id": "evcloudplus.385",
      "access": "r",
      "basetype": "real",
      "description": "while_DDC_Sp_greater_0",
      "format": "",
      "name": "Standby_dT_Manager_total_h",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 44,
      "id": "evcloudplus.42",
      "access": "r",
      "basetype": "real",
      "description": "V_Fb_Rel_2_Vnom",
      "format": "",
      "name": "V_Fb_Rel_2_Vnom",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "percent"
    },
    {
      "Unnamed: 0": 45,
      "id": "evcloudplus.461",
      "access": "r",
      "basetype": "real",
      "description": "Flow_Volume_total_m3",
      "format": "",
      "name": "Flow_Volume_total_m3",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "cubicMetre"
    },
    {
      "Unnamed: 0": 46,
      "id": "evcloudplus.462",
      "access": "r",
      "basetype": "real",
      "description": "moving_average_1h_1updated_value",
      "format": "",
      "name": "dT_movavg_1h1Update_K",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "differentialKelvin"
    },
    {
      "Unnamed: 0": 47,
      "id": "evcloudplus.463",
      "access": "r",
      "basetype": "real",
      "description": "Amount_of_direction_changes_for_actuator",
      "format": "",
      "name": "Act_Dir_Chngs_Counts",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 48,
      "id": "evcloudplus.464",
      "access": "r",
      "basetype": "real",
      "description": "Amount_of_reaching_end_stops_at_0_and_100_percent",
      "format": "",
      "name": "Act_End_Hit_Counts",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 49,
      "id": "evcloudplus.465",
      "access": "r",
      "basetype": "real",
      "description": "Actutor_cummulated_travel_distance_1_equal_100percent_travel",
      "format": "",
      "name": "Act_total_travel_fraction",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 50,
      "id": "evcloudplus.469",
      "access": "r",
      "basetype": "bool",
      "description": "LoopSim_En_B",
      "format": "",
      "name": "LoopSim_En_B",
      "privacy": false,
      "restriction": "",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 51,
      "id": "evcloudplus.470",
      "access": "r",
      "basetype": "bool",
      "description": "Steady_State_in_Control_B",
      "format": "",
      "name": "Steady_State_B",
      "privacy": false,
      "restriction": "",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 52,
      "id": "evcloudplus.511",
      "access": "r",
      "basetype": "real",
      "description": "while_DDC_Sp_greater_0",
      "format": "",
      "name": "dT_Manager_TurnedOff_total_h",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 53,
      "id": "evcloudplus.512",
      "access": "r",
      "basetype": "real",
      "description": "while_DDC_Sp_greater_0",
      "format": "",
      "name": "Full_Load_h",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 54,
      "id": "evcloudplus.513",
      "access": "r",
      "basetype": "real",
      "description": "while_DDC_Sp_greater_0",
      "format": "",
      "name": "Part_Load_h",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": "hour"
    },
    {
      "Unnamed: 0": 55,
      "id": "evcloudplus.70",
      "access": "r",
      "basetype": "int",
      "description": "dT_Manager_Ste_(1=disabled|2=dT_selected_not_active|3=dT_selected_active|4=Flow/dT_selected_not_active|5=Flow/dT_selected_active)",
      "format": "application/vnd.belimo.enum;1|2|3|4|5",
      "name": "dT_Manager_Ste",
      "privacy": false,
      "restriction": "int32",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 56,
      "id": "evcloudplus.85",
      "access": "rw",
      "basetype": "int",
      "description": "DN_Selection (2=DN15, 3=DN20, 4=DN25, 5=DN32, 6=DN40, 7=DN50, 8=DN50(AM), 9=DN65, 10=DN80, 11=DN80(EU), 12=DN100, 13=DN125, 14=DN125(EU), 15=DN150, 16=DN65(ANSI250), 17=DN80(ANSI250), 18=DN100(ANSI250), 19=DN125(ANSI250), 20=DN150(ANSI250))",
      "format": "application/vnd.belimo.enum;2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27",
      "name": "DN_Selection_Write",
      "privacy": false,
      "restriction": "uint8",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 57,
      "id": "evcloudplus.88",
      "access": "r",
      "basetype": "real",
      "description": "OpMode_Err_Override_included_(1=Position_Ctrl|2.1=I_Ctrl|2.2=FF_Ctrl|3=Power_Ctrl)",
      "format": "",
      "name": "OpMode_Err_Override_included_raw_value",
      "privacy": false,
      "restriction": "[-2147483.648,2147483.647]",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    },
    {
      "Unnamed: 0": 58,
      "id": "evcloudplus.91",
      "access": "r",
      "basetype": "bool",
      "description": "Vmin_En_(DDC_Sp=0->Vmin)",
      "format": "",
      "name": "Vmin_Ctrl_En_Write",
      "privacy": false,
      "restriction": "",
      "definedBy": "evcloudplus/1.2",
      "unit": ""
    }
  ]